# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archaeology', '0008_auto_20171126_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museum',
            name='holiday',
            field=models.CharField(blank=True, choices=[('1', 'Sunday'), ('2', 'Monday'), ('3', 'Tuesday'), ('4', 'Wednesday'), ('5', 'Thursday'), ('6', 'Friday'), ('7', 'Saturday')], default=1, max_length=500, null=True),
        ),
    ]
