# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 17:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archaeology', '0010_auto_20171126_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, error_messages={'invalid': 'Please enter name correctly'}, max_length=100, null=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]*$')])),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='news',
        ),
        migrations.AlterField(
            model_name='artifact',
            name='name',
            field=models.CharField(blank=True, error_messages={'invalid': 'Please enter name correctly'}, max_length=100, null=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(blank=True, error_messages={'invalid': 'Please enter author name correctly'}, max_length=100, null=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='books',
            name='name',
            field=models.CharField(blank=True, error_messages={'invalid': 'Please enter name correctly'}, max_length=100, null=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='books',
            name='publisher',
            field=models.CharField(blank=True, error_messages={'invalid': 'Please enter publisher name correctly'}, max_length=100, null=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='excavations',
            name='location',
            field=models.CharField(blank=True, error_messages={'invalid': 'Please enter name correctly'}, max_length=100, null=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='excavations',
            name='name',
            field=models.CharField(blank=True, error_messages={'invalid': 'Please enter name correctly'}, max_length=100, null=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='library',
            name='name',
            field=models.CharField(blank=True, error_messages={'invalid': 'Please enter name correctly'}, max_length=100, null=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='monument',
            name='name',
            field=models.CharField(blank=True, error_messages={'invalid': 'Please enter  name correctly'}, max_length=100, null=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='museum',
            name='name',
            field=models.CharField(blank=True, error_messages={'invalid': 'Please enter name correctly'}, max_length=100, null=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(blank=True, error_messages={'invalid': 'Please enter name correctly'}, max_length=100, null=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='publication',
            name='name',
            field=models.CharField(blank=True, error_messages={'invalid': 'Please enter name correctly'}, max_length=100, null=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='name',
            field=models.CharField(blank=True, error_messages={'invalid': 'Please enter your name'}, max_length=100, null=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='password',
            field=models.CharField(blank=True, error_messages={'invalid': 'Minimum eight characters, at least one uppercase letter, one lowercase letter, one number and one special character'}, max_length=100, null=True, validators=[django.core.validators.RegexValidator(regex='^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[$@$!%*?&])[A-Za-z\\d$@$!%*?&]{8,}')]),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='username',
            field=models.CharField(blank=True, error_messages={'invalid': 'Please enter your name'}, max_length=100, null=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]*$')]),
        ),
    ]
